export enum OrderStatusEnum {
    PENDING = 'PENDING',
    PROCESSING = 'PROCESSING',
    COMPLETED = 'COMPLETED',
    CANCELLED = 'CANCELLED',
    DELIVERING = 'DELIVERING',
    DELIVERED = 'DELIVERED',
}